Post pigeon some changes
Ovikt0r/PostPigeon pull request #1
Opened 2021-09-25 18:16 UTC by Ovikt0r

2021-09-26 16:39 UTC, mihailovprog commented on src/main/java/JavaMailUtil.java
> +            {
Ctrl + Alt + L

2021-09-26 16:39 UTC, mihailovprog commented on src/main/java/JavaMailUtil.java
> +            {
Ненужный блок скобок

2021-09-26 16:40 UTC, mihailovprog commented on src/main/java/JavaMailUtil.java
> +    static boolean isValidEmailAddress(String myAccountEmail) {
Заменить на регулярку

2021-09-26 16:42 UTC, mihailovprog commented on src/main/java/JavaMailUtil.java
> +            System.out.println("Theme of the letter:");
Ну логгер, ну...

2021-09-26 16:42 UTC, mihailovprog commented on src/main/java/SendEmail.java
> +        JavaMailUtil.sendEmail("eternalway256@gmail.com");
Заменить на ввод с консоли

2021-09-26 16:43 UTC, mihailovprog requested changes
Доделать

2021-10-11 16:21 UTC, mihailovprog commented on src/main/java/JavaMailUtil.java
> +            System.out.println("Theme of the letter:");
Логгер не был добавлен

2021-10-11 16:22 UTC, mihailovprog commented on src/main/java/SendEmail.java
> +        JavaMailUtil.sendEmail("eternalway256@gmail.com");
Не было заменено

2021-10-11 16:30 UTC, IliaMikhailovTR commented
Ctrl + Alt + L/O не забывать

2021-10-11 16:42 UTC, mihailovprog commented on src/main/java/JavaMailUtil.java
> +            System.out.println("Theme of the letter:");
Не вижу логгера

2021-10-11 16:42 UTC, mihailovprog commented on src/main/java/JavaMailUtil.java
> +        Scanner sc = new Scanner(System.in);
Не вижу закрытия ресурса

2021-10-11 16:42 UTC, mihailovprog commented on src/main/java/JavaMailUtil.java
> +        System.out.println("Type recepient:");
Опечатка в слове

2021-10-11 16:42 UTC, mihailovprog commented on src/main/java/JavaMailUtil.java
> +    public static final Pattern VALID_EMAIL_ADDRESS_REGEX =
Определение констант должно быть наверху

2021-10-11 16:42 UTC, mihailovprog commented on src/main/java/JavaMailUtil.java
>          return null;
Может быть NPE

2021-10-11 16:42 UTC, mihailovprog commented on src/main/java/JavaMailUtil.java
> +            Scanner sc = new Scanner(System.in);
Зачем 2 сканнера?

2021-10-11 16:42 UTC, mihailovprog commented on src/main/java/JavaMailUtil.java
> +            message.setFrom(new InternetAddress("post.dove.22@hotmail.com"));
Повторение стринги

2021-10-21 16:42 UTC, IliaMikhailovTR requested changes

2021-10-21 16:42 UTC, mihailovprog commented on src/main/java/JavaMailUtil.java
> +    public void setRecipient(String recipient) {
Заменить ломбоком

2021-10-21 16:42 UTC, mihailovprog commented on src/main/java/JavaMailUtil.java
> +        return !matcher.find();
Есть же метод matches()

2021-10-21 16:42 UTC, mihailovprog commented on src/main/java/JavaMailUtil.java
> +        String theme = inputFields.getTheme();
Зачем здесь создание переменной

2021-10-24 17:27 UTC, merged