Task4.1
Ovikt0r/PostPigeon pull request #2
Opened 2021-11-28 17:08 UTC by Ovikt0r

2021-12-02 18:56 UTC, mihailovprog requested changes

2021-12-02 18:56 UTC, mihailovprog commented on src/main/java/Domain.java
> +        RecipientDao recipientDAO = new RecipientDao();
Кажется, здесь это лишнее

2021-12-02 18:56 UTC, mihailovprog commented on src/main/java/Domain.java
> +
Пустые строки

2021-12-02 18:56 UTC, mihailovprog commented on src/main/java/JavaMailUtil.java
> +     public static void sendEmail() throws MessagingException {
Зачем здесь пробел?

2021-12-02 18:56 UTC, mihailovprog commented on src/main/java/connection/UtilConnection.java
> +            e.printStackTrace();
log.error

2021-12-02 18:56 UTC, mihailovprog commented on src/main/java/entity/Recipient.java
> +    public String toString() {
В ломбоке есть аннотация

2021-12-02 18:56 UTC, mihailovprog commented on src/main/java/repository/RecipientDao.java
> +            System.out.println(recipientList);
Не стоит. А если у тебя 1000 записей. Зачем их выводить на печать?

2021-12-02 18:56 UTC, mihailovprog commented on src/main/java/repository/RecipientDao.java
> +            ResultSet resultSet = statement.executeQuery(sql);
Он тоже AutoClosable

2021-12-02 18:56 UTC, mihailovprog commented on src/main/java/repository/RecipientDao.java
> +        try (Connection connection = UtilConnection.getConnection();
Где блок catch?

2021-12-02 18:56 UTC, mihailovprog commented on src/main/java/repository/RecipientDao.java
> +    public void remove(Recipient recipient) throws SQLException {
Переименовать в removeById и передавать id

2021-12-02 18:56 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +        assertEquals(5, recipient2.getId());
Таким образом ты тестируешь геттеры и сеттеры. Нужно снова прочитать объект из бд и смотеть его поля. Более того, можно переопределить метод equals и hashCode, чтобы можно было сравнивать объекты

2021-12-02 18:56 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +        assertEquals(5, recipient2.getId());
+ текущий подход плох тем, что если ты поменяешь строку в 1м месте, в другом она сама не поменяется. Тогда надо вводить переменные, которых будет много. Поэтому подход со сравнением объектов более лаконичный

2021-12-02 18:56 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +        RecipientDao recipientDao2 = new RecipientDao();
Сделать полем

2021-12-02 18:56 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +        List<Recipient> recipientList = new ArrayList<>();
Сделать связку Arrays.asList + builder

2021-12-02 18:56 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +        List<Recipient> testRecipientList = recipientDao2.getAll();
Лучше назвать actualRecipients

2021-12-02 18:56 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +        List<Recipient> recipientList = new ArrayList<>();
Лучше назвать expectedRecipients

2021-12-02 18:56 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +        Recipient recipient;
Зачем здесь разделение?

2021-12-02 18:56 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +
Пустые строки

2021-12-02 18:56 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +            assertEquals("Oskar", recipient3.getName());
Лучше сравнение объектов. Мало ли у тебя update втихаря ещё что-то обновляет

2021-12-02 18:56 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +            recipient1 = recipient2;
Юмора не понял

2021-12-02 18:56 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +    public void update() throws SQLException {
Мне не нравится тест. Нужно записать, прочитать, сравнить. Потом обновить, записать, прочитать, сравнить

2021-12-02 18:56 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +        Recipient recipient2;
Зачем здесь это разделение?

2021-12-02 18:56 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +        assertNull(recipientDAO.getById(6L));
Удаляем с 5м id, а проверяем с 6м?

2021-12-02 18:56 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +            System.out.println("CleanUp is not required");
log

2021-12-28 17:18 UTC, mihailovprog commented
Очень много замечаний не было исправлено

2022-02-06 18:21 UTC, Ovikt0r commented on src/main/java/Domain.java
> +        RecipientDao recipientDAO = new RecipientDao();
ок, убрал

2022-02-06 18:22 UTC, Ovikt0r commented on src/main/java/connection/UtilConnection.java
> +            e.printStackTrace();
заменил !

2022-02-06 19:06 UTC, Ovikt0r commented on src/main/java/repository/RecipientDao.java
> +            System.out.println(recipientList);
убрал

2022-02-06 19:08 UTC, Ovikt0r commented on src/main/java/repository/RecipientDao.java
> +            ResultSet resultSet = statement.executeQuery(sql);
connection, statement, resultSet впомещены в конструкцию try-with-resources

2022-02-06 19:09 UTC, Ovikt0r commented on src/main/java/repository/RecipientDao.java
> +    public void remove(Recipient recipient) throws SQLException {
сделано

2022-02-06 19:11 UTC, Ovikt0r commented on src/main/java/repository/RecipientDao.java
> +        try (Connection connection = UtilConnection.getConnection();
там теперь try-with-resources

2022-02-06 20:11 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +        List<Recipient> testRecipientList = recipientDao2.getAll();
переназвал

2022-02-06 20:17 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +        List<Recipient> recipientList = new ArrayList<>();
Назвал expectedRecipients

2022-02-06 20:19 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +
поубирал что видел

2022-02-06 20:27 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +            assertEquals("Oskar", recipient3.getName());
сравниваю объекты

2022-02-06 20:31 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +    public void update() throws SQLException {
записал методом add(), прочитал методом getById() , сравнил обьекты 
далее засетил name , апдейтнул , снова прочитал , сравнил обьекты

2022-02-06 20:32 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +        Recipient recipient2;
убрал разделение , теперь все манипуляции происходят с обьектом recipient

2022-02-06 20:36 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +        Recipient recipient;
убрал лишнее . создал обьекты expectedRecipient и actualRecipient

2022-02-06 20:37 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +        List<Recipient> recipientList = new ArrayList<>();
сделал так expectedRecipients = new ArrayList<>(Arrays.asList(recipient, recipient2, recipient3, recipient4));
не знаю на сколько правильно ...

2022-02-06 20:37 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +        RecipientDao recipientDao2 = new RecipientDao();
повыносил многие обьекты в поля . но чувствую , что далеко  не все

2022-02-06 20:42 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +        assertEquals(5, recipient2.getId());
сделал сравнение обьектов методом  assertThat () из библиотеки org.assertj.core.api.Assertions

2022-02-08 19:27 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +            System.out.println("CleanUp is not required");
log.info yes )

2022-02-08 19:28 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +        assertNull(recipientDAO.getById(6L));
опечатка , поставил 5ый айди

2022-02-13 17:55 UTC, IliaMikhailovTR commented on src/test/java/repository/RecipientDaoTest.java
> +    Recipient recipient;
В методы

2022-02-13 17:55 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +        Recipient nullRecipient = recipientDAO.getById(5L);
actual

2022-02-13 17:55 UTC, IliaMikhailovTR commented on src/test/java/repository/RecipientDaoTest.java
> +        recipient = new Recipient();
expected

2022-02-13 17:55 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +        expectedRecipient = recipient;
no need

2022-02-13 17:56 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +        assertThat(expectedRecipient).usingRecursiveComparison().isEqualTo(actualRecipient);
assertEquals

2022-02-13 17:59 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +        recipient = new Recipient();
`List<Recipient> expectedRecipients = Arrays.asList(
            Recipient.builder()
                .id(1L)
                .build(),
            Recipient.builder()
                .id(1L)
                .build()
        );`

2022-02-13 18:06 UTC, IliaMikhailovTR commented on src/test/java/repository/RecipientDaoTest.java
> +        assertEquals(5, recipient.getId());
Compare objects

2022-02-13 18:10 UTC, mihailovprog commented on src/main/java/Domain.java
> +public class Domain {
Зочем?

2022-02-22 21:12 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +        assertThat(expectedRecipient).usingRecursiveComparison().isEqualTo(actualRecipient);
убрал предыдущий assertThat библиотеки AssertJ

2022-02-22 21:12 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +        expectedRecipient = recipient;
почистил лишние инициализации обьектов

2022-02-22 21:14 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +        recipient = new Recipient();
поставил параметром результат метода getById(id) в assertNull()

2022-02-22 21:15 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +        Recipient nullRecipient = recipientDAO.getById(5L);
поправил

2022-02-22 21:15 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +    Recipient recipient;
все инициализации обьектов перенес в методы

2022-02-22 21:16 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +        recipient = new Recipient();
создал лист , наполнил билдером

2022-02-22 21:18 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +        assertEquals(5, recipient.getId());
сравниваю объекты в этом методе

2022-02-22 21:19 UTC, Ovikt0r commented on src/main/java/Domain.java
> +public class Domain {
снес этот класс

2022-04-03 16:00 UTC, mihailovprog requested changes

2022-04-03 16:00 UTC, IliaMikhailovTR commented on src/test/java/repository/RecipientDaoTest.java
> +        assertNull(new RecipientDao().getById(5L));
Don't create the object every time. Use the field

2022-04-03 16:00 UTC, IliaMikhailovTR commented on src/test/java/repository/RecipientDaoTest.java
> +        List<Recipient> expectedRecipients = new ArrayList<>(Arrays.asList(new Recipient.Builder()
Just Arrays.asList()

2022-04-03 16:00 UTC, IliaMikhailovTR commented on src/test/java/repository/RecipientDaoTest.java
> +        List<Recipient> expectedRecipients = new ArrayList<>(Arrays.asList(new Recipient.Builder()
new Recipient... from the new line

2022-04-03 16:00 UTC, IliaMikhailovTR commented on src/test/java/repository/RecipientDaoTest.java
> +    public void getAll() throws SQLException {
Make sure that the table is empty

2022-04-03 16:00 UTC, IliaMikhailovTR commented on src/test/java/repository/RecipientDaoTest.java
> +    public void getById() throws SQLException {
How would it work if you clean the database up?
The algorithm should be similar to the "add" test method

2022-04-03 16:00 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +    void cleanUp() throws SQLException, NullPointerException {
I think we should just delete all rows

2022-04-10 17:21 UTC, mihailovprog commented
Use BeforeEach and AfterEach to initialize and drop database

2022-04-10 17:24 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +        assertNull(new RecipientDao().getById(5L));
Extract dao to the class field

2022-04-10 17:26 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +    public void getAll() throws SQLException {
use getAll() method

2022-04-10 17:33 UTC, mihailovprog commented on src/test/java/repository/RecipientDaoTest.java
> +    public void getAll() throws SQLException {
Compare lists sizes()

2022-04-20 19:44 UTC, Ovikt0r commented
> Use BeforeEach and AfterEach to initialize and drop database

Done

2022-04-20 19:45 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +    public void getAll() throws SQLException {
done

2022-04-20 19:45 UTC, Ovikt0r commented on src/test/java/repository/RecipientDaoTest.java
> +        assertNull(new RecipientDao().getById(5L));
done

2022-04-24 16:25 UTC, merged